/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-variant': '#262626',
        'primary-container': '#859aff',
        'primary-fixed-dim': '#718bff',
        outline: '#767575',
        'secondary-fixed-dim': '#ffb0a5',
        'on-surface': '#ffffff',
        'on-tertiary-fixed': '#380033',
        'surface-container-lowest': '#000000',
        'primary-fixed': '#859aff',
        'tertiary-fixed': '#f790e0',
        'tertiary-dim': '#e883d2',
        'surface-bright': '#2c2c2c',
        'on-tertiary': '#6c1561',
        primary: '#97a9ff',
        'on-primary': '#002283',
        secondary: '#ff7162',
        'secondary-dim': '#e2241f',
        'on-error': '#490013',
        tertiary: '#ffa3e9',
        'secondary-fixed': '#ffc3bb',
        'on-secondary-container': '#fff6f4',
        'surface-tint': '#97a9ff',
        'surface-container-high': '#20201f',
        'outline-variant': '#484847',
        surface: '#0e0e0e',
        'error-dim': '#d73357',
        'on-secondary': '#4a0001',
        'tertiary-container': '#f790e0',
        'surface-dim': '#0e0e0e',
        'on-surface-variant': '#adaaaa',
        'tertiary-fixed-dim': '#e883d2',
        'surface-container': '#1a1a1a',
        'on-error-container': '#ffb2b9',
        background: '#0e0e0e',
        'secondary-container': '#c0000a',
        'primary-dim': '#3e65ff',
        'surface-container-low': '#131313',
        'on-tertiary-fixed-variant': '#6a1460',
        'on-tertiary-container': '#5f0656',
        'on-secondary-fixed-variant': '#a60007',
        'on-secondary-fixed': '#700003',
        'on-primary-fixed': '#000000',
        'on-primary-fixed-variant': '#00207e',
        'inverse-on-surface': '#565555',
        'inverse-primary': '#134af1',
        'surface-container-highest': '#262626',
        'on-background': '#ffffff',
        error: '#ff6e84',
        'on-primary-container': '#001867',
        'inverse-surface': '#fcf9f8',
        'error-container': '#a70138',
      },
      fontFamily: {
        headline: ['Plus Jakarta Sans'],
        body: ['Plus Jakarta Sans'],
        label: ['Plus Jakarta Sans'],
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
}
